### ISSUE TITLE
Error at the last step

### ISSUE THREAD

**Issue by donbuche** [webfer/ansible-drupal#43]
Hi there,
I've got the following error when trying to run this command: `ansible-deploy --stage --install --with-assets`

```
TASK [ansistrano.deploy : Rebuild Drupal cache using Drush] ****************************************************
fatal: [93.xxx.xx.xx]: FAILED! => changed=true 
  cmd: |-
    /var/www/clients/client1/web3/web/sites/releases/20240806230002Z/vendor/bin/drush
  delta: '0:00:00.068778'
  end: '2024-08-07 01:00:37.500580'
  msg: non-zero return code
  rc: 255
  start: '2024-08-07 01:00:37.431802'
  stderr: |-
    PHP Warning:  require(/var/www/clients/client1/web3/web/sites/releases/20240806230002Z/vendor/composer/../../web/core/includes/bootstrap.inc): Failed to open stream: No such file or directory in /var/www/clients/client1/web3/web/sites/releases/20240806230002Z/vendor/composer/autoload_real.php on line 45
    PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/clients/client1/web3/web/sites/releases/20240806230002Z/vendor/composer/../../web/core/includes/bootstrap.inc' (include_path='/var/www/clients/client1/web3/web/sites/releases/20240806230002Z/vendor/pear/archive_tar:/var/www/clients/client1/web3/web/sites/releases/20240806230002Z/vendor/pear/console_getopt:/var/www/clients/client1/web3/web/sites/releases/20240806230002Z/vendor/pear/pear-core-minimal/src:/var/www/clients/client1/web3/web/sites/releases/20240806230002Z/vendor/pear/pear_exception:.:/usr/share/php') in /var/www/clients/client1/web3/web/sites/releases/20240806230002Z/vendor/composer/autoload_real.php:45
    Stack trace:
    #0 /var/www/clients/client1/web3/web/sites/releases/20240806230002Z/vendor/composer/autoload_real.php(49): {closure}()
    #1 /var/www/clients/client1/web3/web/sites/releases/20240806230002Z/vendor/autoload.php(25): ComposerAutoloaderInitd8c17506c1cf2e3fcc24fd330f886b02::getLoader()
    #2 /var/www/clients/client1/web3/web/sites/releases/20240806230002Z/vendor/drush/drush/drush.php(123): include('...')
    #3 /var/www/clients/client1/web3/web/sites/releases/20240806230002Z/vendor/drush/drush/drush(4): require('...')
    #4 /var/www/clients/client1/web3/web/sites/releases/20240806230002Z/vendor/bin/drush(119): include('...')
    #5 {main}
      thrown in /var/www/clients/client1/web3/web/sites/releases/20240806230002Z/vendor/composer/autoload_real.php on line 45
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

Seems something related with this task in `tools/ansible/deployafter-symlink.yml`:
````
# Rebuild Drupal cache
- name: Rebuild Drupal cache using Drush
  shell: |
    {{ release_drush_path }}
  args:
    chdir: '{{ release_drupal_path }}'
    executable: /bin/bash
  tags:
    - drupal
  ```

**Comment by donbuche** [comment]
Hi there,

Seems that it only fails in a `--install`.
Once you have deployed the site and you try to run a `--update` it works,

**Comment by webfer** [comment]
@donbuche 
According to their information, the error was apparently generated by a bug in the drush cache clear task, which was resolved in the latest version.
